#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix
basepath=$(cd `dirname $0`; pwd)
plugin_dir=$(dirname $basepath)

which "node" >/dev/null 2>&1
if ! [ $? -eq 0 ]; then
  node_Path=$plugin_dir/node
  new_path=$PATH:$node_Path
  export PATH=$new_path 
fi
$basepath/node_modules/npm/bin/npm-cli.js $@
